package com.lorenzomar3.AQ.content.api;

public enum TipoAResponder {
    PREGUNTA_SIMPLE, VERDADERO_FALSO, SELECCION_UNICA, TEMA, SUBTEMA, OPCION_MULTIPLE, DESPLEGABLE_COMPARTIDO, DESPLEGABLE_INDEPENDIENTE, CUESTIONARIO
}
